# Site settings
name: Flight
title: Flight - An extensible micro-framework for PHP
email: mike@mikecao.com
baseurl: ""
url: "http://flightphp.com"
permalink: pretty

# Build settings
encoding: utf-8
permalink: pretty
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', '.gitignore']
keep_files: ['.git']
